#coding: utf-8
"""
This file is not runnable, but it only consists of various
lists which are required by some other programs.
"""
#
# © Rob W.W. Hooft, 2003
# © Daniel Herding, 2004
# © Ævar Arnfjörð Bjarmason, 2004
# © Andre Engels, 2005
#
# Distribute under the terms of the PSF license.
#

# date formats for various languages, required for interwiki.py with the -days argument
date_format = {
    1: { 
        'af':'%d Januarie',
        'ang':'%d Æfterra Géola',
        'ar':'%d يناير',
        'ast':'%d de xineru',
        'be':'%d студзеня',
        'bg':'%d януари',
        'bs':'%d. januar',
        'ca':'%d de gener',
        'cs':'%d. leden',
        'csb':'%d stëcznika',
        'cy':'%d Ionawr',
        'da':'%d. januar',
        'de':'%d. Januar',
        'el':'%d Ιανουαρίου',
        'en':'January %d',
        'eo':'%d-a de januaro',
        'es':'%d de enero',
        'et':'%d. jaanuar',
        'eu':'Urtarrilaren %d',
        'fi':'%d. tammikuuta',
        'fo':'%d. januar',
        'fr':'%d janvier',
        'fy':'%d jannewaris',
        'ga':'%d Eanáir',
        'gl':'%d de xaneiro',
        'he':'%d בינואר',
        'hr':'%d. siječnja',
        'hu':'Január %d',
        'ia':'%d de januario',
        'id':'%d Januari',
        'ie':'%d januar', # not all months for ie added yet
        'io':'%d di januaro',
        'is':'%d. janúar',
        'it':'%d gennaio',
        'ja':'1月%d日',
        'ka':'%d იანვარი', # ka only January and December added for now
        'ko':'1월 %d일',
        'ku':"%d'ê rêbendanê",
        'la':'%d Ianuarii',
        'lb':'%d. Januar',
        'lt':'Sausio %d',
        'ml':'ജനുവരി %d',
        'nds':'%d Januar',
        'nl':'%d januari',
        'nn':'%d. januar',
        'no':'%d. januar',
        'oc':'%d de geni%%C3%%A8r',
        'pl':'%d stycznia',
        'pt':'%d de Janeiro',
        'ro':'%d ianuarie',
        'ru':'%d января',
        'sk':'%d. január',
        'sl':'%d. januar',
        'sr':'%d. јануар',
        'sv':'%d januari',
        'tl':'Enero %d',
        'tr':'%d Ocak',
        'tt':'%d. Ğínwar',
        'uk':'%d січня',
        'ur':'%d جنوری',
        'vi':'%d tháng 1',
        'wa':"%d di djanvî", # Walloon names depend on the day number; taking the most common form
        'zh':'1月%d日'
    },
    2: {
        'af':'%d Februarie',
        'ang':'%d Solmónaþ',
        'ar':'%d فبراير',
        'ast':'%d de febreru',
        'be':'%d лютага',
        'bg':'%d февруари',
        'bs':'Februar %d',
        'ca':'%d de febrer',
        'cs':'%d. únor',
        'csb':'%d gromicznika',
        'cy':'%d Chwefror',
        'da':'%d. februar',
        'de':'%d. Februar',
        'el':'%d Φεβρουαρίου',
        'en':'February %d',
        'eo':'%d-a de februaro',
        'es':'%d de febrero',
        'et':'%d. veebruar',
        'eu':'Ottsailaren %d',
        'fi':'%d. helmikuuta',
        'fo':'%d. februar',
        'fr':'%d février',
        'fy':'%d febrewaris',
        'ga':'%d Feabhra',
        'gl':'%d de febreiro',
        'he':'%d בפברואר',
        'hr':'%d. veljače',
        'hu':'Február %d',
        'ia':'%d de februario',
        'id':'%d Februari',
        'io':'%d di februaro',
        'is':'%d. febrúar',
        'it':'%d febbraio',
        'ja':'2月%d日',
        'ko':'2월 %d일',
        'ku':"%d'ê reşemiyê",
        'la':'%d Februarii',
        'lb':'%d. Februar',
        'lt':'Vasario %d',
        'ml':'ഫെബ്രുവരി %d',
        'nds':'%d Februar',
        'nl':'%d februari',
        'nn':'%d. februar',
        'no':'%d. februar',
        'oc':'%d de febri%%C3%%A8r',
        'pl':'%d lutego',
        'pt':'%d de Fevereiro',
        'ro':'%d februarie',
        'ru':'%d февраля',
        'sk':'%d. február',
        'sl':'%d. februar',
        'sr':'%d. фебруар',
        'sv':'%d februari',
        'tl':'Pebrero %d',
        'tr':'%d Şubat',
        'tt':'%d. Febräl',
        'uk':'%d лютого',
        'ur':'%d فروری',
        'vi':'%d tháng 2',
        'wa':"%d di fevrî",
        'zh':'2月%d日'
    },
    3: {
        'af':'%d Maart',
        'ang':'%d Hréþmónaþ',
        'ar':'%d مارس',
        'ast':'%d de marzu',
        'be':'%d сакавіка',
        'bg':'%d март',
        'bs':'Mart %d',
        'ca':'%d de_mar%%C3%%A7',
        'cs':'%d. březen',
        'csb':'%d strumiannika',
        'cy':'%d Mawrth',
        'da':'%d. marts',
        'de':'%d. März',
        'en':'March %d',
        'el':'%d Μαρτίου',
        'eo':'%d-a de marto',
        'es':'%d de marzo',
        'et':'%d. märts',
        'eu':'Martxoaren %d',
        'fi':'%d. maaliskuuta',
        'fo':'%d. mars',
        'fr':'%d mars',
        'fy':'%d maart',
        'ga':'%d Márta',
        'gl':'%d de marzo',
        'he':'%d במרץ',
        'hr':'%d. ožujka',
        'hu':'Március %d',
        'ia':'%d de martio',
        'id':'%d Maret',
        'io':'%d di marto',
        'is':'%d. mars',
        'it':'%d marzo',
        'ja':'3月%d日',
        'ko':'3월 %d일',
        'ku':"%d'ê adarê",
        'la':'%d Martii',
        'lb':'%d. Mäerz',
        'lt':'Kovo %d',
        'ml':'മാര്ച് %d',
        'nds':'%d März',
        'nl':'%d maart',
        'nn':'%d. mars',
        'no':'%d. mars',
        'oc':'%d de_mar%%C3%%A7',
        'pl':'%d marca',
        'pt':'%d de Março',
        'ro':'%d martie',
        'ru':'%d марта',
        'sk':'%d. marec',
        'sl':'%d. marec',
        'sr':'%d. март',
        'sv':'%d mars',
        'tl':'Marso %d',
        'tr':'%d Mart',
        'tt':'%d. Mart',
        'uk':'%d березня',
        'ur':'%d مارچ',
        'vi':'%d tháng 3',
        'wa':"%d di måss",
        'zh':'3月%d日'
    },
    4: {
        'af':'%d April',
        'ang':'%d Éastermónaþ',
        'ar':'%d أبريل',
        'ast':"%d d'abril",
        'be':'%d красавіка',
        'bg':'%d април',
        'bs':'April %d',
        'ca':"%d d'abril",
        'cs':'%d. duben',
        'csb':'%d łżëkwiôta',
        'cy':'%d Ebrill',
        'da':'%d. april',
        'de':'%d. April',
        'el':'%d Απριλίου',
        'en':'April %d',
        'eo':'%d-a de aprilo',
        'es':'%d de abril',
        'et':'%d. aprill',
        'eu':'Aprilaren %d',
        'fi':'%d. huhtikuuta',
        'fo':'%d. apríl',
        'fr':'%d avril',
        'fy':'%d april',
        'ga':'%d Aibreán',
        'gl':'%d de abril',
        'he':'%d באפריל',
        'hr':'%d. travnja',
        'hu':'Április %d',
        'ia':'%d de april',
        'id':'%d April',
        'ie':'%d april',
        'io':'%d di aprilo',
        'is':'%d. apríl',
        'it':'%d aprile',
        'ja':'4月%d日',
        'ko':'4월 %d일',
        'ku':"%d'ê avrêlê",
        'la':'%d Aprilis',
        'lb':'%d. Abrëll',
        'lt':'Balandžio %d',
        'ml':'ഏപ്രില് %d',
        'nds':'%d April',
        'nl':'%d april',
        'nn':'%d. april',
        'no':'%d. april',
        'oc':"%d d'abril",
        'pl':'%d kwietnia',
        'pt':'%d de Abril',
        'ro':'%d aprilie',
        'ru':'%d апреля',
        'sk':'%d. apríl',
        'sl':'%d. april',
        'sr':'%d. април',
        'sv':'%d april',
        'tl':'Abríl %d',
        'tr':'%d Nisan',
        'tt':'%d. Äpril',
        'uk':'%d квітня',
        'ur':'%d اپریل',
        'vi':'%d tháng 4',
        'wa':"%d di avri",
        'zh':'4月%d日'
    },
    5: {
        'af':'%d Mei',
        'ang':'%d Þrimilcemónaþ',
        'ar':'%d مايو',
        'ast':'%d de mayu',
        'be':'%d траўня',
        'bg':'%d май',
        'bs':'Maj %d',
        'ca':'%d de maig',
        'cs':'%d. květen',
        'csb':'%d môja',
        'cy':'%d Mai',
        'da':'%d. maj',
        'el':'%d Μαΐου',
        'en':'May %d',
        'et':'%d. mai',
        'eu':'Maiatzaren %d',
        'de':'%d. Mai',
        'eo':'%d-a de majo',
        'es':'%d de mayo',
        'fi':'%d. toukokuuta',
        'fo':'%d. mai',
        'fr':'%d mai',
        'fy':'%d maaie',
        'ga':'%d Bealtaine',
        'gl':'%d de maio',
        'he':'%d במאי',
        'hr':'%d. svibnja',
        'hu':'Május %d',
        'ia':'%d de maio',
        'id':'%d Mei',
        'ie':'%d may',
        'io':'%d di mayo',
        'is':'%d. maí',
        'it':'%d maggio',
        'ja':'5月%d日',
        'ko':'5월 %d일',
        'ku':"%d'ê gulanê",
        'la':'%d Maii',
        'lb':'%d. Mee',
        'lt':'Gegužės %d',
        'ml':'മേയ് %d',
        'nds':'%d Mai',
        'nl':'%d mei',
        'nn':'%d. mai',
        'no':'%d. mai',
        'oc':'%d de mai',
        'pl':'%d maja',
        'pt':'%d de Maio',
        'ro':'%d mai',
        'ru':'%d мая',
        'sk':'%d. máj',
        'sl':'%d. maj',
        'sr':'%d. мај',
        'sv':'%d maj',
        'tl':'Mayo %d',
        'tr':'%d Mayıs',
        'tt':'%d. May',
        'uk':'%d травня',
        'ur':'%d مئ',
        'vi':'%d tháng 5',
        'wa':"%d di may",
        'zh':'5月%d日'
    },
    6: {
        'af':'%d Junie',
        'ang':'%d Séremónaþ',
        'ar':'%d يونيو',
        'ast':'%d de xunu',
        'be':'%d чэрвеня',
        'bg':'%d юни',
        'bs':'Jun %d',
        'ca':'%d de juny',
        'cs':'%d. červen',
        'csb':'%d czerwińca',
        'cy':'%d Mehefin',
        'da':'%d. juni',
        'de':'%d. Juni',
        'el':'%d Ιουνίου',
        'en':'June %d',
        'eo':'%d-a de junio',
        'es':'%d de junio',
        'et':'%d. juuni',
        'eu':'Ekainaren %d',
        'fi':'%d. kesäkuuta',
        'fo':'%d. juni',
        'fr':'%d juin',
        'fy':'%d juny',
        'ga':'%d Meitheamh',
        'gl':'%d de xuño',
        'he':'%d ביוני',
        'hr':'%d. lipnja',
        'hu':'Június %d',
        'ia':'%d de junio',
        'id':'%d Juni',
        'io':'%d di junio',
        'is':'%d. júní',
        'it':'%d giugno',
        'ja':'6月%d日',
        'ko':'6월 %d일',
        'ku':"%d'ê pûşperê",
        'la':'%d Iunii',
        'lb':'%d. Juni',
        'lt':'Birželio %d',
        'ml':'ജൂണ്‍ %d',
        'nds':'%d Juni',
        'nl':'%d juni',
        'nn':'%d. juni',
        'no':'%d. juni',
        'oc':'%d de junh',
        'pl':'%d czerwca',
        'pt':'%d de Junho',
        'ro':'%d iunie',
        'ru':'%d июня',
        'sk':'%d. jún',
        'sl':'%d. junij',
        'sr':'%d. јун',
        'sv':'%d juni',
        'tl':'Hunyo %d',
        'tr':'%d Haziran',
        'tt':'%d. Yün',
        'uk':'%d червня',
        'ur':'%d جون',
        'vi':'%d tháng 6',
        'wa':"%d di djun",
        'zh':'6月%d日'
    },
    7: {
        'af':'%d Julie',
        'ang':'%d Mǽdmónaþ',
        'ar':'%d يوليو',
        'ast':'%d de xunetu',
        'be':'%d ліпеня',
        'bg':'%d юли',
        'bs':'Jul %d',
        'ca':'%d de juliol',
        'cs':'%d. červenec',
        'csb':'%d lëpinca',
        'cy':'%d Gorffenaf',
        'da':'%d. juli',
        'de':'%d. Juli',
        'en':'July %d',
        'el':'%d Ιουλίου',
        'eo':'%d-a de julio',
        'es':'%d de julio',
        'et':'%d. juuli',
        'eu':'Uztailaren %d',
        'fi':'%d. heinäkuuta',
        'fo':'%d. juli',
        'fr':'%d juillet',
        'fy':'%d july',
        'ga':'%d Iúil',
        'gl':'%d de xullo',
        'he':'%d ביולי',
        'hr':'%d. srpnja',
        'hu':'Július %d',
        'ia':'%d de julio',
        'id':'%d Juli',
        'io':'%d di julio',
        'is':'%d. júlí',
        'it':'%d luglio',
        'ja':'7月%d日',
        'ko':'7월 %d일',
        'ku':"%d'ê tîrmehê",
        'la':'%d Iulii',
        'lb':'%d. Juli',
        'lt':'Liepos %d',
        'ml':'ജൂലൈ %d',
        'nds':'%d Juli',
        'nl':'%d juli',
        'nn':'%d. juli',
        'no':'%d. juli',
        'oc':'%d de julhet',
        'pl':'%d lipca',
        'pt':'%d de Julho',
        'ro':'%d iulie',
        'ru':'%d июля',
        'sk':'%d. júl',
        'sl':'%d. julij',
        'sr':'%d. јул',
        'sv':'%d juli',
        'tl':'Hulyo %d',
        'tr':'%d Temmuz',
        'tt':'%d Yül',
        'uk':'%d липня',
        'ur':'%d جلائ',
        'vi':'%d tháng 7',
        'wa':"%d di djulete",
        'zh':'7月%d日'
    },
    8: {
        'af':'%d Augustus',
        'ang':'%d Wéodmónaþ',
        'ar':'%d أغسطس',
        'ast':"%d d'agostu",
        'be':'%d жніўня',
        'bg':'%d август',
        'bs':'Avgust %d',
        'ca':"%d d'agost",
        'cs':'%d. srpen',
        'csb':'%d zélnika',
        'cy':'%d Awst',
        'da':'%d. august',
            'de':'%d. August',
        'el':'%d Αυγούστου',
        'en':'August %d',
        'eo':'%d-a de aŭgusto',
        'es':'%d de agosto',
        'et':'%d. august',
        'eu':'Abuztuaren %d',
        'fi':'%d. elokuuta',
        'fo':'%d. august',
        'fr':'%d août',
        'fy':'%d augustus',
        'ga':'%d Lúnasa',
        'gl':'%d de agosto',
        'he':'%d באוגוסט',
        'hr':'%d. kolovoza',
        'hu':'Augusztus %d',
        'ia':'%d de augusto',
        'id':'%d Agustus',
        'ie':'%d august',
        'io':'%d di agosto',
        'is':'%d. ágúst',
        'it':'%d agosto',
        'ja':'8月%d日',
        'ko':'8월 %d일',
        'ku':"%d'ê gelawêjê",
        'la':'%d Augusti',
        'lb':'%d. August',
        'lt':'Rugpjūčio %d',
        'ml':'ആഗസ്റ്റ്‌ %d',
        'nds':'%d August',
        'nl':'%d augustus',
        'nn':'%d. august',
        'no':'%d. august',
        'oc':"%d d'agost",
        'pl':'%d sierpnia',
        'pt':'%d de Agosto',
        'ro':'%d august',
        'ru':'%d августа',
        'sk':'%d. august',
        'sl':'%d. avgust',
        'sr':'%d. август',
        'sv':'%d augusti',
        'tl':'Agosto %d',
        'tr':'%d Ağustos',
        'tt':'%d. August',
        'uk':'%d серпня',
        'ur':'%d اگست',
        'vi':'%d tháng 8',
        'wa':"%d d' awousse",
        'zh':'8月%d日'
    },
    9: {
        'af':'%d September',
        'ang':'%d Háligmónaþ',
        'ar':'%d سبتمبر',
        'ast':'%d de setiembre',
        'be':'%d верасьня',
        'bg':'%d септември',
        'bs':'Septembar %d',
        'ca':'%d de setembre',
        'cs':'%d. září',
        'csb':'%d séwnika',
        'cy':'%d Medi',
        'da':'%d. september',
        'de':'%d. September',
        'el':'%d Σεπτεμβρίου',
        'en':'September %d',
        'eo':'%d-a de septembro',
        'es':'%d de septiembre',
        'et':'%d. september',
        'eu':'Irailaren %d',
        'fi':'%d. syyskuuta',
        'fo':'%d. september',
        'fr':'%d septembre',
        'fy':'%d septimber',
        'ga':'%d Meán Fómhair',
        'gl':'%d de setembro',
        'he':'%d בספטמבר',
        'hr':'%d. rujna',
        'hu':'Szeptember %d',
        'ia':'%d de septembre',
        'id':'%d September',
        'io':'%d di septembro',
        'is':'%d. september',
        'it':'%d settembre',
        'ja':'9月%d日',
        'ko':'9월 %d일',
        'ku':"%d'ê rezberê",
        'la':'%d Septembris',
        'lb':'%d. September',
        'lt':'Rugsėjo %d',
        'ml':'സപ്തന്പര് %d',
        'nds':'%d September',
        'nl':'%d september',
        'nn':'%d. september',
        'no':'%d. september',
        'oc':'%d de setembre',
        'pl':'%d września',
        'pt':'%d de Setembro',
        'ro':'%d septembrie',
        'ru':'%d сентября',
        'sk':'%d. september',
        'sl':'%d. september',
        'sr':'%d. септембар',
        'sv':'%d september',
        'tl':'Setyembre %d',
        'tr':'%d Eylül',
        'tt':'%d. Sentäber',
        'uk':'%d вересня',
        'ur':'%d ستمب',
        'vi':'%d tháng 9',
        'wa':'%d di setimbe',
        'zh':'9月%d日'
    },
    10:{
        'af':'%d Oktober',
        'ang':'%d Winterfylleþ',
        'ar':'%d أكتوبر',
        'ast':"%d d'ochobre",
        'be':'%d кастрычніка',
        'bg':'%d октомври',
        'bs':'Oktobar %d',
        'ca':"%d d'octubre",
        'cs':'%d. říjen',
        'csb':'%d rujana',
        'cy':'%d Hydref',
        'da':'%d. oktober',
        'de':'%d. Oktober',
        'el':'%d Οκτωβρίου',
        'en':'October %d',
        'eo':'%d-a de oktobro',
        'es':'%d de octubre',
        'et':'%d. oktoober',
        'eu':'Urriaren %d',
        'fi':'%d. lokakuuta',
        'fo':'%d. oktober',
        'fr':'%d octobre',
        'fy':'%d oktober',
        'ga':'%d Deireadh Fómhair',
        'gl':'%d de outubro',
        'he':'%d באוקטובר',
        'hr':'%d. listopada',
        'hu':'Október %d',
        'ia':'%d de octobre',
        'id':'%d Oktober',
        'io':'%d di oktobro',
        'is':'%d. október',
        'it':'%d ottobre',
        'ja':'10月%d日',
        'ko':'10월 %d일',
        'ku':"%d'ê kewçêrê",
        'la':'%d Octobris',
        'lb':'%d. Oktober',
        'lt':'Spalio %d',
        'ml':'ഒക്ടോബര് %d',
        'nds':'%d Oktober',
        'nl':'%d oktober',
        'nn':'%d. oktober',
        'no':'%d. oktober',
        'oc':"%d d'octobre",
        'pl':'%d października',
        'pt':'%d de Outubro',
        'ro':'%d octombrie',
        'ru':'%d октября',
        'sk':'%d. október',
        'sl':'%d. oktober',
        'sr':'%d. октобар',
        'sv':'%d oktober',
        'tl':'Oktubre %d',
        'tr':'%d Ekim',
        'tt':'%d. Öktäber',
        'uk':'%d жовтня',
        'ur':'%d اکتوبر',
        'vi':'%d tháng 10',
        'wa':"%d d' octôbe",
        'zh':'10月%d日'
    },
    11:{
        'af':'%d November',
        'ang':'%d Blótmónaþ',
        'ar':'%d نوفمبر',
        'ast':'%d de payares',
        'be':'%d лістапада',
        'bg':'%d ноември',
        'bs':'Novembar %d',
        'ca':'%d de novembre',
        'cs':'%d. listopad',
        'csb':'%d lëstopadnika',
        'cy':'%d Tachwedd',
        'da':'%d. november',
        'de':'%d. November',
        'el':'%d Νοεμβρίου',
        'en':'November %d',
        'eo':'%d-a de novembro',
        'es':'%d de noviembre',
        'et':'%d. november',
        'eu':'Azaroaren %d',
        'fi':'%d. marraskuuta',
        'fo':'%d. november',
        'fr':'%d novembre',
        'fy':'%d novimber',
        'ga':'%d Samhain',
        'gl':'%d de novembro',
        'he':'%d בנובמבר',
        'hr':'%d studenog',
        'hu':'November %d',
        'ia':'%d de novembre',
        'id':'%d November',
        'io':'%d di novembro',
        'it':'%d novembre',
        'is':'%d. nóvember',
        'ja':'11月%d日',
        'ko':'11월 %d일',
        'ku':"%d'ê sermawezê",
        'la':'%d Novembris',
        'lb':'%d. November',
        'lt':'Lapkričio  %d',
        'ml':'നവന്പര് %d',
        'nds':'%d November',
        'nl':'%d november',
        'nn':'%d. november',
        'no':'%d. november',
        'oc':'%d de novembre',
        'pl':'%d listopada',
        'pt':'%d de Novembro',
        'ro':'%d noiembrie',
        'ru':'%d ноября',
        'sk':'%d. november',
        'sl':'%d. november',
        'sr':'%d. новембар',
        'sv':'%d november',
        'tl':'Nobyembre %d',
        'tr':'%d Kasım',
        'tt':'%d. Nöyäber',
        'uk':'%d листопада',
        'ur':'%d نومب',
        'vi':'%d tháng 11',
        'wa':'%d di nôvimbe',
        'zh':'11月%d日'
    },
    12:{
        'af':'%d Desember',
        'ang':'%d Géolmónaþ',
        'ar':'%d ديسمبر',
        'ast':"%d d'avientu",
        'be':'%d сьнежня',
        'bg':'%d декември',
        'bs':'Decembar %d',
        'ca':'%d de desembre',
        'cs':'%d. prosinec',
        'csb':'%d gòdnika',
        'cy':'%d Rhagfyr',
        'da':'%d. december',
        'de':'%d. Dezember',
        'el':'%d Δεκεμβρίου',
        'en':'December %d',
        'eo':'%d-a de decembro',
        'es':'%d de diciembre',
        'et':'%d. detsember',
        'eu':'Abenduaren %d',
        'fi':'%d. joulukuuta',
        'fo':'%d. desember',
        'fr':'%d décembre',
        'fy':'%d desimber',
        'ga':'%d Mí na Nollag',
        'gl':'%d de decembro',
        'he':'%d בדצמבר',
        'hr':'%d prosinca',
        'hu':'December %d',
        'ia':'%d de decembre',
        'id':'%d Desember',
        'io':'%d di decembro',
        'is':'%d. desember',
        'it':'%d dicembre',
        'ja':'12月%d日',
        'ka':'%d დეკემბერი',
        'ko':'12월 %d일',
        'ku':"%d'ê berfanbarê",
        'la':'%d Decembris',
        'lb':'%d. Dezember',
        'lt':'Gruodžio %d',
        'ml':'ഡിസന്പര് %d',
        'nds':'%d Dezember',
        'nl':'%d december',
        'nn':'%d. desember',
        'no':'%d. desember',
        'oc':'%d de decembre',
        'pl':'%d grudnia',
        'pt':'%d de Dezembro',
        'ro':'%d decembrie',
        'ru':'%d декабря',
        'sk':'%d. december',
        'sl':'%d. december',
        'sr':'%d. децембар',
        'sv':'%d december',
        'tl':'Disyembre %d',
        'tr':'%d Aralık',
        'tt':'%d.Dekäber',
        'uk':'%d грудня',
        'ur':'%d دسمب',
        'vi':'%d tháng 12',
        'wa':'%d di decimbe',
        'zh':'12月%d日'
    }
}

class FormatDate(object):
    def __init__(self, site):
        self.site = site

    def __call__(self, m, d):
        import wikipedia
        return wikipedia.html2unicode((date_format[m][self.site.lang]) % d,
               site = self.site)
    
# number of days in each month, required for interwiki.py with the -days argument
days_in_month = {
    1:  31,
    2:  29,
    3:  31,
    4:  30,
    5:  31,
    6:  30,
    7:  31,
    8:  31,
    9:  30,
    10: 31,
    11: 30,
    12: 31
}

# format for dates B.C., required for interwiki.py with the -years argument and for titletranslate.py
yearBCfmt = {
        'af':'%d v.Chr.',
        #'bg':'%d &#1075;. &#1087;&#1088;.&#1085;.&#1077;.', # All years BC redirect to centuries for bg:
        'bs':'%d p.ne.',
        'ca':'%d aC',
        'da':'%d f.Kr.',
        'de':'%d v. Chr.',
        'en':'%d BC',
        'eo':'-%d',
        'es':'%d adC',
        'et':'%d eKr',
        'fi':'%d eaa',
        'fo':'%d f. Kr.',
        'fr':'-%d',
        'he':'%d &#1500;&#1508;&#1504;&#1492;"&#1505;',
        'hr':'%d p.n.e.',
        'is':'%d f. Kr.',
        'it':'%d AC',
        'la':'%d a.C.n',
        'lb':'-%d',
        'nds':'%d v. Chr.',
        'nl':'%d v. Chr.',
        'nn':'-%d',
        'no':'%d f.Kr.',
        'pl':'%d p.n.e.',
        'pt':'%d a.C.',
        'ro':'%d î.Hr.'
        'ru':'%d &#1076;&#1086; &#1085;.&#1101;.',
        'sl':'%d pr. n. št.',
        'sr':'%d. &#1087;&#1085;&#1077;.',
        'sv':'%d f.Kr.',
        'zh':'&#21069;%d&#24180;'
} # No default

# For all languages the maximal value a year BC can have; before this date the
# language switches to decades or centuries
maxyearBC = {
        'ca':500,
        'de':400,
        'en':499,
        'nl':1000,
        'pl':776
        }

# format for dates A.D., required for interwiki.py with the -years argument
# if a language is not listed here, interwiki.py assumes '%d' as the date format.
yearADfmt = {
        'ja':'%d&#24180;',
        'zh':'%d&#24180;',
        'ko':'%d&#45380;',
        'minnan':'%d n&icirc;',
        'ur':'%d&#1587;&#1576;&#1605;'
}
         
         
# date format translation list required for titletranslate.py and for pagelist.py
datetable = {
    'nl':{
        'januari':1,
        'februari':2,
        'maart':3,
        'april':4,
        'mei':5,
        'juni':6,
        'juli':7,
        'augustus':8,
        'september':9,
        'oktober':10,
        'november':11,
        'december':12
    },
}

