#!/bin/sh
# $Id$
dt=`date +"%Y%m%d"`
/bin/rm -rf temp
mkdir temp
cd temp
cvs -d `cat ../CVS/Root` export -D now -d pywikipediabot pywikipedia
/bin/rm -f $HOME/snapshot-$dt.zip
zip -rv $HOME/snapshot-$dt.zip pywikipediabot/*
tar -cvzf $HOME/snapshot-$dt.tar.gz pywikipediabot/*
