# -*- coding: utf-8  -*-
import config, family, urllib

#
# The Uncyclomedia family, assorted encyclopedi.as from the Uncyclopedia series.
# This file contains a full set of (currently) fifty languages, excluding forks,
# redirects and mirrors.
#
# Note that some of the wikia in this set are known to have badly incomplete,
# missing or incorrect interwiki maps. Do *not* attempt to invoke interwiki.py
# on Uncyclopedia-related wikis unless you have verified availability of
# links for all language pairs that you will plan to use as interwikis.
#

class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'uncyclopedia'

        self.langs = {
            'ar': 'beidipedia.wikia.com',
            'ast':'nunyepedia.wikia.com',
            'bn': 'bn.uncyc.org',
            'bg': 'bg.oxypedia.net',
            'bs': 'bs.neciklopedija.org',
            'ca': 'valenciclopedia.wikia.com',
            'common': 'commons.uncyclomedia.org',
            'cs': 'necyklopedie.wikia.com',
            'cy': 'cy.uncyclopedia.org.uk',
            'da': 'spademanns.wikia.com',
            'de': 'de.uncyclopedia.org',
            'el': 'frikipaideia.wikia.com',
            'en': 'uncyclopedia.org',
            'eo': 'neciklopedio.wikia.com',
            'es': 'inciclopedia.wikia.com',
            'et': 'ebatsuklopeedia.org',
            'fa': 'fa.uncyc.org',
            'fi': 'hikipedia.info',
            'fr': 'desencyclopedie.wikia.com',
            'got':'unsaiklopedia.org',
            'he': 'eincyclopedia.wikia.com',
            'hr': 'hr.neciklopedija.org',
            'hu': 'unciklopedia.org',
            'id': 'tolololpedia.wikia.com',
            'info': 'uncyclopedia.info',
            'it': 'nonciclopedia.wikia.com',
            'ja': 'ansaikuropedia.org',
            'jv': 'ndhablek.wikia.com',
            'ko': 'uncyclopedia.kr',
            'la': 'uncapaedia.wikia.com',
            'lb': 'kengencyclopedia.org',
            'lt': 'juokopedija.org',
            'lv': 'lv.neciklopedija.org',
            'meta': 'meta.uncyclomedia.org',
            'mg': 'hatsiklopedia.org',
            'mk': 'mk.neciklopedija.org',
            'nl': 'oncyclopedia.net',
            'nn': 'ikkepedia.org',
            'no': 'ikkepedia.org',
            'pl': 'nonsensopedia.wikia.com',
            'pt': 'desciclopedia.ws',
            'ro': 'uncyclopedia.ro',
            'ru': 'absurdopedia.wikia.com',
            'sk': 'necyklopedia.wikia.com',
            'sl': 'butalopedija.org',
            'sr': 'sr.neciklopedija.org',
            'su': 'su.goblogpedia.wikia.com',
            'sv': 'psyklopedin.org',
            'th': 'th.uncyclopedia.info',
            'tr': 'yansiklopedi.org',
            'uk': 'inciklopedia.org',
            'yi': 'keinziklopedie.wikia.com',
            'zh-hk': 'uncyclopedia.hk',
            'zh-tw':'uncyclopedia.tw',
            'zh': 'zh.uncyclopedia.wikia.com',
        }

        #
        # project namespaces & custom namespace lists
        #

        self.namespaces[-2] = {
            '_default': u'Media',
            'ar': u'ميديا',
            'bs': u'Medija',
            'cs': u'Média',
            'el': u'Μέσο',
            'et': u'Meedia',
            'fa': u'مدیا',
            'fr': u'Média',
            'he': u'מדיה',
            'hu': u'Media',
            'ko': u'미디어',
            'mk': u'Медија',
            'nn': u'Medium',
            'ru': u'Медиа',
            'sk': u'Médiá',
            'sr': u'Медија',
            'su': u'Média',
            'th': u'สื่อ',
            'uk': u'Медіа',
            'yi': u'מעדיע',
            'zh-hk': u'媒體',
            'zh-tw': u'媒體',
        }

        self.namespaces[-1] = {
            '_default': u'Special:',
            'ar': u'خاص',
            'ast': u'Especial',
            'bs': u'Posebno',
            'ca': u'Especial',
            'common': u'Special',
            'cs': u'Speciální',
            'cy': u'Arbennig',
            'da': u'Speciel',
            'de': u'Spezial',
            'el': u'Ειδικό',
            'eo': u'Speciala',
            'es': u'Especial',
            'et': u'Eri',
            'fa': u'ویژه',
            'fi': u'Toiminnot',
            'fr': u'Spécial',
            'got': u'Special',
            'he': u'מיוחד',
            'hu': u'Speciális',
            'id': u'Istimewa',
            'it': u'Speciale',
            'ja': u'Special',
            'jv': u'Astamiwa',
            'ko': u'특수기능',
            'la': u'Specialis',
            'lb': u'Spezial',
            'meta': u'Special',
            'mg': u'Special',
            'mk': u'Специјални',
            'nn': u'Spesial',
            'pl': u'Specjalna',
            'ro': u'Special',
            'ru': u'Служебная',
            'sk': u'Špeciálne',
            'sl': u'Posebno',
            'sr': u'Посебно',
            'su': u'Husus',
            'sv': u'Special',
            'uk': u'Спеціальна',
            'yi': u'באַזונדער',
            'zh': u'Special',
            'zh-hk': u'特殊',
            'zh-tw': u'特殊',
        }

        self.namespaces[1] = {
            'ar': u'نقاش',
            'ast': u'Alderique',
            'bs': u'Razgovor',
            'ca': u'Discussió',
            'common': u'Talk',
            'cs': u'Diskuse',
            'cy': u'Sgwrs',
            'da': u'Diskussion',
            'de': u'Diskussion',
            'el': u'Συζήτηση',
            'eo': u'Diskuto',
            'es': u'Discusión',
            'et': u'Arutelu',
            'fa': u'بحث',
            'fi': u'Keskustelu',
            'fr': u'Discuter',
            'got': u'Talk',
            'he': u'שיחה',
            'hu': u'Vita',
            'id': u'Pembicaraan',
            'it': u'Discussione',
            'ja': u'Talk',
            'jv': u'Dhiskusi',
            'ko': u'토론',
            'la': u'Disputatio',
            'lb': u'Diskussioun',
            'lv': u'Diskusija',
            'meta': u'Talk',
            'mg': u'Discuter',
            'mk': u'Разговор',
            'nn': u'Diskusjon',
            'pl': u'Dyskusja',
            'ro': u'Discuţie',
            'ru': u'Обсуждение',
            'sk': u'Diskusia',
            'sl': u'Pogovor',
            'sr': u'Разговор',
            'su': u'Obrolan',
            'sv': u'Diskussion',
            'th': u'พูดคุย',
            'uk': u'Обговорення',
            'yi': u'רעדן',
            'zh': u'Talk',
            'zh-hk': u'討論',
            'zh-tw': u'討論',
        }

        self.namespaces[2] = {
            'ar': u'مستخدم',
            'ast': u'Usuariu',
            'bs': u'Korisnik',
            'ca': u'Usuari',
            'common': u'User',
            'cs': u'Uživatel',
            'cy': u'Defnyddiwr',
            'da': u'Bruger',
            'de': u'Benutzer',
            'el': u'Χρήστης',
            'eo': u'Vikipediisto',
            'es': u'Usuario',
            'et': u'Kasutaja',
            'fa': u'کاربر',
            'fi': u'Käyttäjä',
            'fr': u'Utilisateur',
            'got': u'User',
            'he': u'משתמש',
            'hu': u'User',
            'id': u'Pengguna',
            'it': u'Utente',
            'ja': u'利用者',
            'jv': u'Panganggo',
            'ko': u'사용자',
            'la': u'Usor',
            'lb': u'Benotzer',
            'lv': u'Lietotājs',
            'meta': u'User',
            'mg': u'Utilisateur',
            'mk': u'Корисник',
            'nn': u'Bruker',
            'pl': u'Użytkownik',
            'ro': u'Utilizator',
            'ru': u'Участник',
            'sk': u'Redaktor',
            'sl': u'Uporabnik',
            'sr': u'Корисник',
            'su': u'Pamaké',
            'sv': u'Användare',
            'uk': u'Користувач',
            'yi': u'באַניצער',
            'zh': u'User',
            'zh-hk': u'用戶',
            'zh-tw': u'用戶',
        }

        self.namespaces[3] = {
            'ar': u'نقاش المستخدم',
            'ast': u'Usuariu alderique',
            'bs': u'Razgovor sa korisnikom',
            'ca': u'Usuari Discussió',
            'common': u'User talk',
            'cs': u'Uživatel diskuse',
            'cy': u'Sgwrs Defnyddiwr',
            'da': u'Brugerdiskussion',
            'de': u'Benutzer Diskussion',
            'el': u'Συζήτηση χρήστη',
            'eo': u'Vikipediista diskuto',
            'es': u'Usuario Discusión',
            'et': u'Kasutaja arutelu',
            'fa': u'بحث کاربر',
            'fi': u'Keskustelu käyttäjästä',
            'fr': u'Discussion Utilisateur',
            'got': u'User talk',
            'he': u'שיחת משתמש',
            'hu': u'User talk',
            'id': u'Pembicaraan Pengguna',
            'it': u'Discussioni utente',
            'ja': u'利用者‐会話',
            'jv': u'Dhiskusi Panganggo',
            'ko': u'사용자토론',
            'la': u'Disputatio Usoris',
            'lb': u'Benotzer Diskussioun',
            'lv': u'Lietotāja diskusija',
            'meta': u'User talk',
            'mg': u'Discussion Utilisateur',
            'mk': u'Разговор со корисник',
            'nn': u'Brukerdiskusjon',
            'pl': u'Dyskusja użytkownika',
            'ro': u'Discuţie Utilizator',
            'ru': u'Обсуждение участника',
            'sk': u'Diskusia s redaktorom',
            'sl': u'Uporabniški pogovor',
            'sr': u'Разговор са корисником',
            'su': u'Obrolan pamaké',
            'sv': u'Användardiskussion',
            'th': u'คุยกับผู้ใช้',
            'uk': u'Обговорення користувача',
            'yi': u'באַניצער רעדן',
            'zh': u'User talk',
            'zh-hk': u'用戶討論',
            'zh-tw': u'用戶討論',
        }

        self.namespaces[4] = {
            '_default': u'Uncyclopedia',
            'ar': u'بيضيپيديا',
            'ast': u'Nunyepedia',
            'bg': u'Oxypedia',
            'bn': u'Uncyclopedia',
            'bs': u'Neciklopedija',
            'ca': u'Valenciclopèdia',
            'common': u'UnCommons',
            'cs': u'Necyklopedie',
            'cy': u'Celwyddoniadur',
            'da': u'Spademanns Leksikon',
            'de': u'Uncyclopedia',
            'el': u'Φρικηπαίδεια',
            'en': u'Uncyclopedia',
            'eo': u'Neciklopedio',
            'es': u'Inciclopedia',
            'et': u'Ebatsüklopeedia',
            'fa': u'نانشنامه',
            'fi': u'Hikipedia',
            'fr': u'Désencyclopédie',
            'got': u'Unsaiklopedia',
            'he': u'איןציקלופדיה',
            'hr': u'Neciklopedija',
            'hu': u'Unciklopédia',
            'id': u'Tolololpedia',
            'info': u'Uncyclopaedia',
            'it': u'Nonciclopedia',
            'ja': u'Uncyclopedia',
            'jv': u'Ndhablek',
            'ko': u'백괴사전',
            'la': u'Uncapaedia',
            'lb': u'Kengencyclopedia',
            'lt': u'Juokopediją',
            'lv': u'Neciklopēdija',
            'meta': u'UnMeta',
            'mg': u'Hatsiklopedia',
            'mk': u'Нециклопедий',
            'nl': u'Oncyclopedie',
            'nn': u'Ikkepedia',
            'no': u'Ikkepedia',
            'pl': u'Nonsensopedia',
            'pt': u'Desciclopédia',
            'ro': u'Neciclopedie',
            'ru': u'Абсурдопедия',
            'sk': u'Necyklopédia',
            'sl': u'Butalopedija',
            'sr': u'Нециклопедија',
            'su': u'Goblogpedia Wiki',
            'sv': u'Psyklopedin',
            'th': u'ไร้สาระนุกรม',
            'tr': u'Yansiklopedi',
            'uk': u'Інциклопедія',
            'yi': u'קיינציקלאָפעדיע',
            'zh': u'伪基百科',
            'zh-hk': u'偽基百科',
            'zh-tw': u'偽基百科',
        }

        self.namespaces[5] = {
            'ar': u'نقاش بيضيپيديا',
            'ast': u'Nunyepedia alderique',
            'bg': u'Oxypedia беседа',
            'bn': u'Uncyclopedia আলাপ',
            'bs': u'Razgovor s Neciklopedija',
            'ca': u'Valenciclopèdia Discussió',
            'common': u'UnCommon talk',
            'cs': u'Necyklopedie diskuse',
            'cy': u'Sgwrs Celwyddoniadur',
            'da': u'Spademanns Leksikon-diskussion',
            'de': u'Uncyclopedia Diskussion',
            'el': u'Φρικηπαίδεια συζήτηση',
            'en': u'Uncyclopedia talk',
            'eo': u'Neciklopedio diskuto',
            'es': u'Inciclopedia Discusión',
            'et': u'Ebatsüklopeedia arutelu',
            'fa': u'بحث نانشنامه',
            'fi': u'Keskustelu Hikipediasta',
            'fr': u'Discussion Désencyclopédie',
            'got': u'Unsaiklopedia talk',
            'he': u'שיחת איןציקלופדיה',
            'hr': u'Razgovor Neciklopedija',
            'hu': u'Unciklopédia vita',
            'id': u'Pembicaraan Tolololpedia',
            'info': u'Uncyclopædia talk',
            'it': u'Discussioni Nonciclopedia',
            'ja': u'Uncyclopedia talk',
            'jv': u'Dhiskusi Ndhablek',
            'ko': u'백괴사전토론',
            'la': u'Disputatio Uncapaediae',
            'lb': u'Kengencyclopedia Diskussioun',
            'lt': u'Juokopediją aptarimas',
            'lv': u'Neciklopēdija diskusija',
            'meta': u'UnMeta talk',
            'mg': u'Discussion Hatsiklopedia',
            'mk': u'Разговор за Нециклопедий',
            'nl': u'Overleg Oncyclopedie',
            'nn': u'Ikkepedia-diskusjon',
            'no': u'Ikkepedia-diskusjon',
            'pl': u'Dyskusja Nonsensopedia',
            'pt': u'Desciclopédia Discussão',
            'ro': u'Discuţie Neciclopedie',
            'ru': u'Обсуждение Абсурдопедии',
            'sk': u'Diskusia k Necyklopédia',
            'sl': u'Pogovor o Butalopedija',
            'sr': u'Разговор о Нециклопедија',
            'su': u'Obrolan Goblogpedia Wiki',
            'sv': u'Psyklopedindiskussion',
            'th': u'คุยเรื่องไร้สาระนุกรม',
            'tr': u'Yansiklopedi tartışma',
            'uk': u'Обговорення Інциклопедії',
            'yi': u'קיינציקלאָפעדיע רעדן',
            'zh': u'伪基百科 talk',
            'zh-hk': u'偽基百科討論',
            'zh-tw': u'偽基百科討論',
        }

        self.namespaces[6] = {
            'ar': u'ملف',
            'ast': u'Archivu',
            'bs': u'Slika',
            'ca': u'Fitxer',
            'common': u'Image',
            'cs': u'Soubor',
            'cy': u'Delwedd',
            'da': u'Billede',
            'de': u'Datei',
            'el': u'Αρχείο',
            'eo': u'Dosiero',
            'es': u'Archivo',
            'et': u'Pilt',
            'fa': u'تصویر',
            'fi': u'Kuva',
            'fr': u'Fichier',
            'got': u'Image',
            'he': u'קובץ',
            'hu': u'Kép',
            'id': u'Berkas',
            'info': u'File',
            'it': u'File',
            'ja': u'Image',
            'jv': u'Gambar',
            'ko': u'파일',
            'la': u'Fasciculus',
            'lb': u'Bild',
            'lv': u'Attēls',
            'meta': u'Image',
            'mg': u'Image',
            'mk': u'Слика',
            'nn': u'Bilde',
            'pl': u'Plik',
            'ro': u'Imagine',
            'ru': u'Файл',
            'sk': u'Súbor',
            'sl': u'Slika',
            'sr': u'Слика',
            'su': u'Gambar',
            'sv': u'Bild',
            'uk': u'Зображення',
            'yi': u'טעקע',
            'zh': u'File',
            'zh-hk': u'圖像',
            'zh-tw': u'圖像',
        }

        self.namespaces[7] = {
            'ar': u'نقاش الملف',
            'ast': u'Archivu alderique',
            'bs': u'Razgovor o slici',
            'ca': u'Fitxer Discussió',
            'common': u'Image talk',
            'cs': u'Soubor diskuse',
            'cy': u'Sgwrs Delwedd',
            'da': u'Billeddiskussion',
            'de': u'Datei Diskussion',
            'el': u'Συζήτηση αρχείου',
            'eo': u'Dosiera diskuto',
            'es': u'Archivo Discusión',
            'et': u'Pildi arutelu',
            'fa': u'بحث تصویر',
            'fi': u'Keskustelu kuvasta',
            'fr': u'Discussion Fichier',
            'got': u'Image talk',
            'he': u'שיחת קובץ',
            'hu': u'Kep vita',
            'id': u'Pembicaraan Berkas',
            'info': u'File talk',
            'it': u'Discussioni file',
            'ja': u'画像‐ノート',
            'jv': u'Dhiskusi Gambar',
            'ko': u'파일토론',
            'la': u'Disputatio Fasciculi',
            'lb': u'Bild Diskussioun',
            'lv': u'Attēla diskusija',
            'meta': u'Image talk',
            'mg': u'Discussion Image',
            'mk': u'Разговор за слика',
            'nn': u'Bildediskusjon',
            'pl': u'Dyskusja pliku',
            'ro': u'Discuţie Imagine',
            'ru': u'Обсуждение файла',
            'sk': u'Diskusia k súboru',
            'sl': u'Pogovor o sliki',
            'sr': u'Разговор о слици',
            'su': u'Obrolan gambar',
            'sv': u'Bilddiskussion',
            'th': u'คุยเรื่องภาพ',
            'uk': u'Обговорення зображення',
            'yi': u'טעקע רעדן',
            'zh': u'File talk',
            'zh-hk': u'圖像討論',
            'zh-tw': u'圖像討論',
        }

        self.namespaces[8] = {
            'ar': u'ميدياويكي',
            'ast': u'MediaWiki',
            'bs': u'MedijaViki',
            'ca': u'MediaWiki',
            'common': u'MediaWiki',
            'cs': u'MediaWiki',
            'cy': u'MediaWici',
            'da': u'MediaWiki',
            'de': u'MediaWiki',
            'el': u'MediaWiki',
            'eo': u'MediaWiki',
            'es': u'MediaWiki',
            'et': u'MediaWiki',
            'fa': u'مدیاویکی',
            'fi': u'MediaWiki',
            'fr': u'MediaWiki',
            'got': u'MediaWiki',
            'he': u'מדיה ויקי',
            'hu': u'MediaWiki',
            'id': u'MediaWiki',
            'it': u'MediaWiki',
            'ja': u'MediaWiki',
            'jv': u'MediaWiki',
            'ko': u'미디어위키',
            'la': u'MediaWiki',
            'lb': u'MediaWiki',
            'meta': u'MediaWiki',
            'mg': u'MediaWiki',
            'mk': u'МедијаВики',
            'nn': u'MediaWiki',
            'pl': u'MediaWiki',
            'ro': u'MediaWiki',
            'ru': u'MediaWiki',
            'sk': u'MediaWiki',
            'sl': u'MediaWiki',
            'sr': u'МедијаВики',
            'su': u'MédiaWiki',
            'sv': u'MediaWiki',
            'th': u'มีเดียวิกิ',
            'uk': u'MediaWiki',
            'yi': u'מעדיעװיקי',
            'zh': u'MediaWiki',
            'zh-hk': u'媒體偽基',
            'zh-tw': u'媒體偽基',
        }

        self.namespaces[9] = {
            'ar': u'نقاش ميدياويكي',
            'ast': u'MediaWiki alderique',
            'bn': u'MediaWiki আলাপ',
            'bs': u'Razgovor o MedijaVikiju',
            'ca': u'MediaWiki Discussió',
            'common': u'MediaWiki talk',
            'cs': u'MediaWiki diskuse',
            'cy': u'Sgwrs MediaWici',
            'da': u'MediaWiki-diskussion',
            'de': u'MediaWiki Diskussion',
            'el': u'Συζήτηση MediaWiki',
            'eo': u'MediaWiki diskuto',
            'es': u'MediaWiki Discusión',
            'et': u'MediaWiki arutelu',
            'fa': u'بحث مدیاویکی',
            'fi': u'Keskustelu MediaWiki',
            'fr': u'Discussion MediaWiki',
            'got': u'MediaWiki talk',
            'he': u'שיחת מדיה ויקי',
            'hu': u'MediaWiki talk',
            'id': u'Pembicaraan MediaWiki',
            'it': u'Discussioni MediaWiki',
            'ja': u'MediaWiki‐ノート',
            'jv': u'Dhiskusi MediaWiki',
            'ko': u'미디어위키토론',
            'la': u'Disputatio MediaWiki',
            'lb': u'MediaWiki Diskussioun',
            'lv': u'MediaWiki diskusija',
            'meta': u'MediaWiki talk',
            'mg': u'Discussion MediaWiki',
            'mk': u'Разговор за МедијаВики',
            'nn': u'MediaWiki-diskusjon',
            'pl': u'Dyskusja MediaWiki',
            'ro': u'Discuţie MediaWiki',
            'ru': u'Обсуждение MediaWiki',
            'sk': u'Diskusia k MediaWiki',
            'sl': u'Pogovor o MediaWiki',
            'sr': u'Разговор о МедијаВикију',
            'su': u'Obrolan MédiaWiki',
            'sv': u'MediaWikidiskussion',
            'th': u'คุยเรื่องมีเดียวิกิ',
            'uk': u'Обговорення MediaWiki',
            'yi': u'מעדיעװיקי רעדן',
            'zh': u'MediaWiki talk',
            'zh-hk': u'媒體偽基討論',
            'zh-tw': u'媒體偽基討論',
        }

        self.namespaces[10] = {
            'ar': u'قالب',
            'ast': u'Plantía',
            'bs': u'Šablon',
            'ca': u'Plantilla',
            'common': u'Template',
            'cs': u'Šablona',
            'cy': u'Nodyn',
            'da': u'Skabelon',
            'de': u'Vorlage',
            'el': u'Πρότυπο',
            'eo': u'Ŝablono',
            'es': u'Plantilla',
            'et': u'Mall',
            'fa': u'الگو',
            'fi': u'Malline',
            'fr': u'Modèle',
            'got': u'Template',
            'he': u'תבנית',
            'hu': u'Sablon',
            'id': u'Templat',
            'it': u'Template',
            'ja': u'Template',
            'jv': u'Cithakan',
            'ko': u'틀',
            'la': u'Formula',
            'lb': u'Schabloun',
            'lv': u'Veidne',
            'meta': u'Template',
            'mg': u'Modèle',
            'mk': u'Шаблон',
            'nn': u'Mal',
            'pl': u'Szablon',
            'ro': u'Format',
            'ru': u'Шаблон',
            'sk': u'Šablóna',
            'sl': u'Predloga',
            'sr': u'Шаблон',
            'su': u'Citakan',
            'sv': u'Mall',
            'th': u'แม่แบบ',
            'uk': u'Шаблон',
            'yi': u'מוסטער',
            'zh': u'Template',
            'zh-hk': u'範本',
            'zh-tw': u'範本',
        }

        self.namespaces[11] = {
            'ar': u'نقاش القالب',
            'ast': u'Plantía alderique',
            'bs': u'Razgovor o šablonu',
            'ca': u'Plantilla Discussió',
            'common': u'Template talk',
            'cs': u'Šablona diskuse',
            'cy': u'Sgwrs Nodyn',
            'da': u'Skabelondiskussion',
            'de': u'Vorlage Diskussion',
            'el': u'Συζήτηση προτύπου',
            'eo': u'Ŝablona diskuto',
            'es': u'Plantilla Discusión',
            'et': u'Malli arutelu',
            'fa': u'بحث الگو',
            'fi': u'Keskustelu mallineesta',
            'fr': u'Discussion Modèle',
            'got': u'Template talk',
            'he': u'שיחת תבנית',
            'hu': u'Sablon vita',
            'id': u'Pembicaraan Templat',
            'it': u'Discussioni template',
            'ja': u'Template‐ノート',
            'jv': u'Dhiskusi Cithakan',
            'ko': u'틀토론',
            'la': u'Disputatio Formulae',
            'lb': u'Schabloun Diskussioun',
            'lv': u'Veidnes diskusija',
            'meta': u'Template talk',
            'mg': u'Discussion Modèle',
            'mk': u'Разговор за шаблон',
            'nn': u'Maldiskusjon',
            'pl': u'Dyskusja szablonu',
            'ro': u'Discuţie Format',
            'ru': u'Обсуждение шаблона',
            'sk': u'Diskusia k šablóne',
            'sl': u'Pogovor o predlogi',
            'sr': u'Разговор о шаблону',
            'su': u'Obrolan citakan',
            'sv': u'Malldiskussion',
            'th': u'คุยเรื่องแม่แบบ',
            'uk': u'Обговорення шаблону',
            'yi': u'מוסטער רעדן',
            'zh': u'Template talk',
            'zh-hk': u'範本討論',
            'zh-tw': u'範本討論',
        }

        self.namespaces[12] = {
            'ar': u'مساعدة',
            'ast': u'Aida',
            'bs': u'Pomoć',
            'ca': u'Ajuda',
            'common': u'Help',
            'cs': u'Nápověda',
            'cy': u'Cymorth',
            'da': u'Hjælp',
            'de': u'Hilfe',
            'el': u'Βοήθεια',
            'eo': u'Helpo',
            'es': u'Ayuda',
            'et': u'Juhend',
            'fa': u'راهنما',
            'fi': u'Ohje',
            'fr': u'Aide',
            'got': u'Help',
            'he': u'מדריך',
            'hu': u'Segítség',
            'id': u'Bantuan',
            'it': u'Aiuto',
            'ja': u'Help',
            'jv': u'Pitulung',
            'ko': u'도움말',
            'la': u'Auxilium',
            'lb': u'Hëllef',
            'lv': u'Palīdzība',
            'meta': u'Help',
            'mg': u'Aide',
            'mk': u'Помош',
            'nn': u'Hjelp',
            'pl': u'Pomoc',
            'ro': u'Ajutor',
            'ru': u'Справка',
            'sk': u'Pomoc',
            'sl': u'Pomoč',
            'sr': u'Помоћ',
            'su': u'Pitulung',
            'sv': u'Hjälp',
            'th': u'วิธีใช้',
            'uk': u'Довідка',
            'yi': u'הילף',
            'zh': u'Help',
            'zh-hk': u'協助',
            'zh-tw': u'協助',
        }

        self.namespaces[13] = {
            'ar': u'نقاش المساعدة',
            'ast': u'Aida alderique',
            'bs': u'Razgovor o pomoći',
            'ca': u'Ajuda Discussió',
            'common': u'Help talk',
            'cs': u'Nápověda diskuse',
            'cy': u'Sgwrs Cymorth',
            'da': u'Hjælp-diskussion',
            'de': u'Hilfe Diskussion',
            'el': u'Συζήτηση βοήθειας',
            'eo': u'Helpa diskuto',
            'es': u'Ayuda Discusión',
            'et': u'Juhendi arutelu',
            'fa': u'بحث راهنما',
            'fi': u'Keskustelu ohjeesta',
            'fr': u'Discussion Aide',
            'got': u'Help talk',
            'he': u'שיחת מדריך',
            'hu': u'Segítség vita',
            'id': u'Pembicaraan Bantuan',
            'it': u'Discussioni aiuto',
            'ja': u'Help‐ノート',
            'jv': u'Dhiskusi Pitulung',
            'ko': u'도움말토론',
            'la': u'Disputatio Auxilii',
            'lb': u'Hëllef Diskussioun',
            'lv': u'Palīdzības diskusija',
            'meta': u'Help talk',
            'mg': u'Discussion Aide',
            'mk': u'Разговор за помош',
            'nn': u'Hjelpdiskusjon',
            'pl': u'Dyskusja pomocy',
            'ro': u'Discuţie Ajutor',
            'ru': u'Обсуждение справки',
            'sk': u'Diskusia k pomoci',
            'sl': u'Pogovor o pomoči',
            'sr': u'Разговор о помоћи',
            'su': u'Obrolan pitulung',
            'sv': u'Hjälpdiskussion',
            'th': u'คุยเรื่องวิธีใช้',
            'uk': u'Обговорення довідки',
            'yi': u'הילף רעדן',
            'zh': u'Help talk',
            'zh-hk': u'協助討論',
            'zh-tw': u'協助討論',
        }

        self.namespaces[14] = {
            'ar': u'تصنيف',
            'ast': u'Categoría',
            'bs': u'Kategorija',
            'ca': u'Categoria',
            'common': u'Category',
            'cs': u'Kategorie',
            'cy': u'Categori',
            'da': u'Kategori',
            'de': u'Kategorie',
            'el': u'Κατηγορία',
            'eo': u'Kategorio',
            'es': u'Categoría',
            'et': u'Kategooria',
            'fa': u'رده',
            'fi': u'Luokka',
            'fr': u'Catégorie',
            'got': u'Category',
            'he': u'קטגוריה',
            'hu': u'Kategória',
            'id': u'Kategori',
            'it': u'Categoria',
            'ja': u'Category',
            'jv': u'Kategori',
            'ko': u'분류',
            'la': u'Categoria',
            'lb': u'Kategorie',
            'lv': u'Kategorija',
            'meta': u'Category',
            'mg': u'Catégorie',
            'mk': u'Категорија',
            'nn': u'Kategori',
            'pl': u'Kategoria',
            'ro': u'Categorie',
            'ru': u'Категория',
            'sk': u'Kategória',
            'sl': u'Kategorija',
            'sr': u'Категорија',
            'su': u'Kategori',
            'sv': u'Kategori',
            'th': u'หมวดหมู่',
            'uk': u'Категорія',
            'yi': u'קאַטעגאָריע',
            'zh': u'Category',
            'zh-hk': u'分類',
            'zh-tw': u'分類',
        }

        self.namespaces[15] = {
            'ar': u'نقاش التصنيف',
            'ast': u'Categoría alderique',
            'bg': u'Категория беседа',
            'bs': u'Razgovor o kategoriji',
            'ca': u'Categoria Discussió',
            'common': u'Category talk',
            'cs': u'Kategorie diskuse',
            'cy': u'Sgwrs Categori',
            'da': u'Kategoridiskussion',
            'de': u'Kategorie Diskussion',
            'el': u'Συζήτηση κατηγορίας',
            'eo': u'Kategoria diskuto',
            'es': u'Categoría Discusión',
            'et': u'Kategooria arutelu',
            'fa': u'بحث رده',
            'fi': u'Keskustelu luokasta',
            'fr': u'Discussion Catégorie',
            'got': u'Category talk',
            'he': u'שיחת קטגוריה',
            'hu': u'Kategória vita',
            'id': u'Pembicaraan Kategori',
            'it': u'Discussioni categoria',
            'ja': u'Category‐ノート',
            'jv': u'Dhiskusi Kategori',
            'ko': u'분류토론',
            'la': u'Disputatio Categoriae',
            'lb': u'Kategorie Diskussioun',
            'lv': u'Kategorijas diskusija',
            'meta': u'Category talk',
            'mg': u'Discussion Catégorie',
            'mk': u'Разговор за категорија',
            'nn': u'Kategoridiskusjon',
            'pl': u'Dyskusja kategorii',
            'ro': u'Discuţie Categorie',
            'ru': u'Обсуждение категории',
            'sk': u'Diskusia ku kategórii',
            'sl': u'Pogovor o kategoriji',
            'sr': u'Разговор о категорији',
            'su': u'Obrolan kategori',
            'sv': u'Kategoridiskussion',
            'th': u'คุยเรื่องหมวดหมู่',
            'uk': u'Обговорення категорії',
            'yi': u'קאַטעגאָריע רעדן',
            'zh': u'Category talk',
            'zh-hk': u'分類討論',
            'zh-tw': u'分類討論',
        }

        self.namespaces[16] = {
          'fi': u'Foorumi',
          'got': u'Forum',
          'info': u'Game',
#      'ko': u'漢字',
          'meta': u'UnSource',
          'nl': u'Portaal',
          'pt': u'Esplanada',
          'th': u'อันไซโคลพีเดีย',
          'zh-hk': u'偽基新聞',
          'zh-tw': u'偽基新聞'
        }

        self.namespaces[17] = {
          'fi': u'Keskustelu foorumista',
          'got': u'Forum gawaurdja',
          'info': u'Game talk',
#      'ko': u'討論',
          'meta': u'UnSource talk',
          'nl': u'Overleg portaal',
          'pt': u'Esplanada Discussão',
          'th': u'คุยเรื่องอันไซโคลพีเดีย',
          'zh-hk': u'偽基新聞討論',
          'zh-tw': u'偽基新聞討論'
        }

        self.namespaces[18] = {
            '_default': '',
            'fi': u'Hikinews',
            'got': u'���df30���df42���df3c���df30���df39���df49',
            'ko': u'백괴나라',
            'meta': u'UnSpecies',
            'nl': u'OnNieuws',
            'pt': u'Fatos',
            'th': u'ไร้ข่าว',
            'zh-hk': u'偽基辭典',
        }

        self.namespaces[19] = {
            '_default': '',
            'fi': u'Keskustelu Hikinewseistä',
            'got': u'���df30���df42���df3c���df30���df39���df49 ���df32���df30���df45���df30���df3f���df42���df33���df3e���df30',
            'ko': u'백괴나라토론',
            'meta': u'UnSpecies talk',
            'nl': u'Overleg OnNieuws',
            'pt': u'Fatos Discussão',
            'th': u'คุยเรื่องไร้ข่าว',
            'zh-hk': u'偽基辭典討論',
        }

        self.namespaces[20] = {
            '_default': '',
            'fi': u'Hiktionary',
            'got': u'���df46���df30���df39���df30���df3d���df45���df30���df3f���df42���df33���df30���df31���df49���df3a���df30',
            'meta': u'Namespace',
            'nl': u'Onwoordenboek',
            'pt': u'Forum',
            'th': u'ไร้วิทยาลัย',
            'zh-hk': u'動漫遊戲',
        }

        self.namespaces[21] = {
            '_default': '',
            'fi': u'Keskustelu Hiktionarysta',
            'got': u'���df46���df30���df39���df30���df3d���df45���df30���df3f���df42���df33���df30���df31���df49���df3a���df30 ���df32���df30���df45���df30���df3f���df42���df33���df3e���df30',
            'meta': u'Namespace talk',
            'nl': u'Overleg Onwoordenboek',
            'pt': u'Forum Discussão',
            'th': u'คุยเรื่องไร้วิทยาลัย',
            'zh-hk': u'動漫遊戲討論',
        }

        self.namespaces[22] = {
            'fi': u'Hikikirjasto',
            'meta': u'UnN',
            'nl': u'OnBoeken',
            'th': u'ไร้พจนานุกรม',
            'zh-hk': u'偽基文庫',
            'zh-tw': u'偽基文庫',
        }

        self.namespaces[23] = {
            'fi': u'Keskustelu hikikirjasta',
            'meta': u'UnN talk',
            'nl': u'Overleg OnBoeken',
            'th': u'คุยเรื่องไร้พจนานุกรม',
            'zh-hk': u'偽基文庫討論',
            'zh-tw': u'偽基文庫討論',
        }

        self.namespaces[24] = {
            'fi': u'Hikisitaatit',
            'meta': u'Forum',
            'th': u'ไร้ชีวประวัติ',
            'zh-hk': u'主題展館',
        }

        self.namespaces[25] = {
            'fi': u'Keskustelu hikisitaatista',
            'meta': u'Forum talk',
            'th': u'คุยเรื่องไร้ชีวประวัติ',
            'zh-hk': u'主題展館討論',
        }

        self.namespaces[26] = {
          'fi': u'Hömppäpedia',
          'th': u'สภาน้ำชา',
          'zh-hk': u'論壇',
          'zh-tw': u'論壇'
        }

        self.namespaces[27] = {
          'fi': u'Höpinä hömpästä',
          'th': u'คุยเรื่องสภาน้ำชา',
          'zh-hk': u'論壇討論',
          'zh-tw': u'論壇討論'
        }

        self.namespaces[28] = {
          'fi': u'Hikipeli',
          'nl': u'Ongerijmd',
          'th': u'บอร์ด',
          'zh-hk': u'詞意分道',
          'zh-tw': u'詞意分道'
        }

        self.namespaces[29] = {
          'fi': u'Hihitys Hikipelistä',
          'th': u'คุยเรื่องบอร์ด',
          'zh-hk': u'詞意分道討論',
          'zh-tw': u'詞意分道討論'
        }

        self.namespaces[30] = {
          'pt': u'Deslivros',
          'th': u'ไร้ซอร์ซ',
          'zh-hk': u'臺語',
          'zh-tw': u'臺語'
        }

        self.namespaces[31] = {
          'pt': u'Deslivros Discussão',
          'th': u'คุยเรื่องไร้ซอร์ซ',
          'zh-hk': u'臺語討論',
          'zh-tw': u'臺語討論'
        }

        self.namespaces[32] = {
          'ja': u'Portal',
          'pt': u'Desentrevistas',
          'th': u'ไร้คำคม',
          'zh-hk': u'香港語',
          'zh-tw': u'香港語'
        }

        self.namespaces[33] = {
          'ja': u'Portal talk',
          'pt': u'Desentrevistas Discussão',
          'th': u'คุยเรื่องไร้คำคม',
          'zh-hk': u'香港語討論',
          'zh-tw': u'香港語討論'
        }

        self.namespaces[34] = {
          'th': u'ไร้ภาพ',
          'zh-hk': u'書面語',
          'zh-tw': u'書面語'
        }

        self.namespaces[35] = {
          'th': u'คุยเรื่องไร้ภาพ',
          'zh-hk': u'書面語討論',
          'zh-tw': u'書面語討論'
        }

        self.namespaces[36] = {
            'th': u'สถานีย่อย',
            'zh-hk': u'偽基書籍',
        }

        self.namespaces[37] = {
            'th': u'คุยเรื่องสถานีย่อย',
            'zh-hk': u'偽基書籍討論',
        }

        self.namespaces[100] = {
            'de': u'UnNews',
            'he': u'איןציטוט',
            'ko': u'백괴게임',
            'nn': u'Ikkenytt',
            'no': u'Ikkenytt',
            'pl': u'Cytaty',
            'sv': u'PsykNyheter',
        }

        self.namespaces[101] = {
            'de': u'UnNews Diskussion',
            'he': u'שיחת איןציטוט',
            'ko': u'백괴게임토론',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'sv': u'PsykNyheter diskussion',
        }

        self.namespaces[102] = {
            'de': u'Undictionary',
            'en': u'UnNews',
            'ja': u'UnNews',
            'ko': u'포럼',
            'nn': u'Ikktionary',
            'no': u'Ikktionary',
            'pl': u'NonNews',
            'sv': u'Forum',
            'tr': u'YanHaber',
        }

        self.namespaces[103] = {
            'de': u'Undictionary Diskussion',
            'en': u'UnNews talk',
            'ja': u'UnNews talk',
            'ko': u'포럼토론',
            'nn': u'Ikktionary-diskusjon',
            'no': u'Ikktionary-diskusjon',
            'pl': u'Dyskusja NonNews',
            'sv': u'Forumdiskussion',
        }

        self.namespaces[104] = {
            'de': u'UnBooks',
            'en': u'Undictionary',
            'ja': u'Undictionary',
            'ko': u'백괴뉴스',
            'pl': u'Nonźródła',
            'sv': u'Psyktionary',
        }

        self.namespaces[105] = {
            'de': u'UnBooks Diskussion',
            'en': u'Undictionary talk',
            'ja': u'Undictionary talk',
            'ko': u'백괴뉴스토론',
            'pl': u'Dyskusja nonźródeł',
            'sv': u'Psyktionary diskussion',
        }

        self.namespaces[106] = {
            '_default': '',
            'en': u'Game',
            'ja': u'Game',
            'ko': u'백괴낱말사전',
            'pl': u'Słownik',
            'pt': u'Desnotícias',
            'sv': u'PsykCitat',
        }

        self.namespaces[107] = {
            'en': u'Game talk',
            'ja': u'Game talk',
            'ko': u'백괴낱말사전토론',
            'pl': u'Dyskusja słownika',
            'pt': u'Desnotícias Discussão',
            'sv': u'PsykCitat diskussion',
        }

        self.namespaces[108] = {
            'en': u'Babel',
            'ko': u'해설',
            'pl': u'Gra',
            'pt': u'Jogo',
            'sv': u'Spel',
        }

        self.namespaces[109] = {
            'en': u'Babel talk',
            'ko': u'해설토론',
            'pl': u'Dyskusja gry',
            'pt': u'Jogo Discussão',
            'sv': u'Speldiskussion',
        }

        self.namespaces[110] = {
            '_default': u'Forum',
            'ar': u'Forum',
            'ast': u'Forum',
            'ca': u'Forum',
            'cs': u'Forum',
            'da': u'Forum',
            'de': u'Forum',
            'el': u'Forum',
            'en': u'Forum',
            'eo': u'Forum',
            'es': u'Forum',
            'fr': u'Forum',
            'he': u'בית קפה',
            'id': u'Forum',
            'it': u'Forum',
            'ja': u'Forum',
            'jv': u'Forum',
            'ko': u'백괴식당',
            'la': u'Forum',
            'nn': u'Forum',
            'no': u'Forum',
            'pl': u'Forum',
            'pt': u'Descionário',
            'ru': u'Форум',
            'sk': u'Forum',
            'su': u'Forum',
            'sv': u'PsykBöcker',
            'tr': u'Astroloji',
            'yi': u'Forum',
        }

        self.namespaces[111] = {
            '_default': u'Forum talk',
            'ar': u'Forum talk',
            'ast': u'Forum talk',
            'ca': u'Forum talk',
            'cs': u'Forum talk',
            'da': u'Forumdiskussion',
            'de': u'Forum talk',
            'el': u'Forum talk',
            'en': u'Forum talk',
            'eo': u'Forum talk',
            'es': u'Forum talk',
            'fr': u'Discussion Forum',
            'he': u'שיחת בית קפה',
            'id': u'Forum talk',
            'it': u'Forum talk',
            'ja': u'Forum talk',
            'jv': u'Forum talk',
            'ko': u'백괴식당토론',
            'la': u'Forum talk',
            'nn': u'Forum-diskusjon',
            'no': u'Forum-diskusjon',
            'pl': u'Dyskusja forum',
            'pt': u'Descionário Discussão',
            'ru': u'Обсуждение форума',
            'sk': u'Forum talk',
            'su': u'Forum talk',
            'sv': u'PsykBöckerdiskussion',
            'tr': u'Astroloji tartışma',
            'yi': u'Forum talk',
        }

        self.namespaces[112] = {
            'cs': u'Regál',
            'en': u'UnTunes',
            'es': u'Incinoticias',
            'fr': u'Désinformation',
            'he': u'איןספר',
            'it': u'NonNotizie',
            'ja': u'UnTunes',
            'ko': u'백괴우주',
            'nn': u'Hvordan',
            'no': u'Hvordan',
            'pl': u'Portal',
            'zh': u'伪基新闻',
        }

        self.namespaces[113] = {
            'cs': u'Regál diskuse',
            'en': u'UnTunes talk',
            'es': u'Incinoticias Discusión',
            'fr': u'Discussion Désinformation',
            'he': u'שיחת איןספר',
            'it': u'Discussioni NonNotizie',
            'ja': u'UnTunes talk',
            'ko': u'백괴우주토론',
            'nn': u'Hvordan-diskusjon',
            'no': u'Hvordan-diskusjon',
            'pl': u'Dyskusja portalu',
            'zh': u'伪基新闻 talk',
        }

        self.namespaces[114] = {
            'cs': u'Necykloverzita',
            'es': u'Incitables',
            'fr': u'Portail',
            'he': u'איןחדש',
            'nn': u'Hvorfor',
            'no': u'Hvorfor',
            'pl': u'Poradnik',
            'zh': u'伪基文库',
        }

        self.namespaces[115] = {
            'cs': u'Necykloverzita diskuse',
            'es': u'Incitables Discusión',
            'fr': u'Discussion Portail',
            'he': u'שיחת איןחדש',
            'nn': u'Hvorfor-diskusjon',
            'no': u'Hvorfor-diskusjon',
            'pl': u'Dyskusja poradnika',
            'zh': u'伪基文库 talk',
        }

        self.namespaces[120] = {
            'he': u'איןמילון',
            'it': u'NonCitazioni',
            'pt': u'Privado',
        }

        self.namespaces[121] = {
            'he': u'שיחת איןמילון',
            'it': u'Discussioni NonCitazioni',
            'pt': u'Privado Discussão',
        }

        self.namespaces[122] = {
            'he': u'איןמינים',
            'it': u'NonDizionario',
        }

        self.namespaces[123] = {
            'he': u'שיחת איןמינים',
            'it': u'Discussioni NonDizionario',
        }

        # A few selected big languages for things that we do not want to loop over
        # all languages. This is only needed by the titletranslate.py module, so
        # if you carefully avoid the options, you could get away without these
        # for another wiki family.
        self.languages_by_size  = ['en', 'ja', 'pt', 'it', 'pl', 'fr', 'fi', 'es', 'zh-tw', 'de', 'no']     

    def hostname(self,code):
        return self.langs[code]

    def path(self, code):
        if code == 'ko':
           return '/w/index.php'
        return '/index.php'

    def version(self, code):
        return '1.12'

    def apipath(self, code):
        if code == 'ko':
           return '/w/api.php'
        return '/api.php'

    def code2encoding(self,code):
        return 'utf-8'

    def shared_image_repository(self, code):
        return ('common', 'common')
