#!/bin/bash
# Simple bash script to converts tabs in our python files into 4 spaces
# (c) 2009 Nicolas Dumazet
# License: WTFPL Version 2
for file in $(grep -Rl [[:cntrl:]] . | grep -v ".svn" | grep "\.py$"); do sed -i 's/\t/    /g' $file; done
